server:
  port: 8080

spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  redis:
    host: localhost
    port: 6379
    password:

bailian:
  workspace:
  appId:
  apiKey:
